# Generated by Django 4.1.7 on 2023-03-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
