# Generated by Django 4.1.7 on 2023-03-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('F', 'Finished'), ('D', 'Delivered'), ('W', 'Waiting')], default='W', max_length=40),
        ),
    ]
