# Generated by Django 4.1.7 on 2023-03-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('F', 'Finished'), ('D', 'Delivered'), ('W', 'Waiting')], default='Waiting', max_length=40),
        ),
    ]
