# Generated by Django 4.1.7 on 2023-03-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Aceepted', 'Accepted'), ('Rejected', 'Rejected'), ('Finished', 'Finished'), ('Delivered', 'Delivered'), ('Waiting', 'Waiting')], default='Waiting', max_length=40),
        ),
    ]
