# Generated by Django 4.1.7 on 2023-03-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
    ]
